schemaVersion: 2.0.0

fileExistenceTests:
  - name: 'app directory should not exist'
    path: '/app'
    shouldExist: false
  - name: 'main binary should exist'
    path: '/main'
    shouldExist: true

metadataTest:
  cmd: ['/main']
  entrypoint: []
  labels:
    - key: 'org.opencontainers.image.source'
      value: 'https://github.com/gawbul/kubernetes-example-application'
    - key: 'org.opencontainers.image.description'
      value: 'Kubernetes Example Application'
    - key: 'org.opencontainers.image.title'
      value: 'Kubernetes Example Application'
  exposedPorts: ['8080']
  user: ''
  volumes: []
  workdir: '/'
